/*
HEADER CONTAINS ADDRESSES DEFINITION OF EXCEPTION NEW AND OLD AREAS FOR UMPS
*/
#ifndef EXC_AREA_H
#define EXC_AREA_H

#define EXCV_BASE 0x20000000
#define STATE_T_SIZE 140

#define INT_OLDAREA EXCV_BASE
#define INT_NEWAREA (EXCV_BASE + STATE_T_SIZE)
#define TLB_OLDAREA (EXCV_BASE + (2 * STATE_T_SIZE))
#define TLB_NEWAREA (EXCV_BASE + (3 * STATE_T_SIZE))
#define PGMTRAP_OLDAREA (EXCV_BASE + (4 * STATE_T_SIZE))
#define PGMTRAP_NEWAREA (EXCV_BASE + (5 * STATE_T_SIZE))
#define SYSBK_OLDAREA (EXCV_BASE + (6 * STATE_T_SIZE))
#define SYSBK_NEWAREA (EXCV_BASE + (7 * STATE_T_SIZE))

#endif /* EXC_AREA_H */